### ISSUE TITLE
Улучшение функционала бота

### ISSUE THREAD

**Issue by Gold778b** [mirea-ninja/mirea-teacher-schedule-bot#30]
Реализовать функцию определения занятости/незанятости кабинета с возможностью вывода проводимого занятия, группы, преподавателя.

**Comment by necrosskull** [comment]
* Функционал был добавлен в (#32)

**Comment by Gold778b** [comment]
Доработать возможность поиска по аудиториям кампуса Стромынка.

**Comment by MintyRoma** [comment]
> Доработать возможность поиска по аудиториям кампуса Стромынка.

Зачастую проблемы с аудиториями и парами в корпусах вне Вернадского 78 связаны с неправильным заполнением расписания сотрудниками кампуса, а также отсутствием у университета полной базы аудиторий (либо нежеланием делиться подобной информацией со студентами). В данный момент подобный функционал осуществляется через расписание. Улучшения, для повышения точности, запланированы, но дата реализации пока неизвестна.
Отслеживайте новости Mirea Ninja, чтобы знать когда данный функционал появится полностью)
